services:
  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./teste.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "7000:5432"

  java:
     build: ./java/
     volumes:
      - ./java/src:/main
     command: ./mvnw spring-boot:run

  java-tests:
    build:
      context: ./java/
    command: ["./mvnw", "test"]
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:[7000:5432]/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: example

  frontend:
     build: ./frontend/
     volumes:
      - ./frontend/src:/usr/src/app/src
      - /usr/src/app/node_modules
     command: ng serve --host 0.0.0.0 --poll 2000 --watch
     ports:
      - "4200:4200"

  # frontend-tests:
  #   build:
  #     context: ./frontend/
  #   command: ng test --watch=false --browsers=ChromeHeadless
  #   depends_on:
  #     - webserver
  #   environment:
  #     - CHROME_BIN=/usr/bin/chromium-browser

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8010:80"

volumes:
  pgdata:
